services:
  movecar-app:
    build: .
    container_name: movecar_app
    restart: always
    ports:
      - "13000:3000" 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_URL=redis://movecar-redis:6379
      - ADMIN_PASSWORD=你的复杂密码 # 管理后台密码
      
      # (如果需要解决 Bark 阻断，取消下面两行的注释并填入代理)
      #- HTTP_PROXY=http://192.168.1.X:7890
      #- HTTPS_PROXY=http://192.168.1.X:7890

    depends_on:
      - movecar-redis

  movecar-redis:
    image: redis:7-alpine
    container_name: movecar_redis
    restart: always
    volumes:
      - redis_data:/data 
    command: redis-server --appendonly yes 

volumes:
  redis_data: