// src/routes/api.js
const express = require('express');
const router = express.Router();
const redisClient = require('../utils/redis');
const { CONFIG, getUserConfig, getBaseDomain, getSystemSettings } = require('../utils/config');
const { generateMapUrls } = require('../utils/geo');
const Notifier = require('../services/notifier');

// 💡 15款高定海报模板数据 (默认底座)
const defaultTemplates = [
   { id: 'vertical_modern', name: '经典竖版', thumb: '📱', html: '<div style="width: 800px; height: 1200px; background: white; border-radius: 40px; overflow: hidden; position: relative; box-shadow: 0 0 0 2px #f3f4f6; font-family: sans-serif; box-sizing: border-box;"><div style="position: absolute; top: 0; left: 0; width: 800px; height: 480px; background: #10b981; border-radius: 0 0 60px 60px;"></div><div style="position: absolute; top: 140px; left: 0; width: 800px; text-align: center; color: white; font-size: 76px; font-weight: 900; letter-spacing: 4px; line-height: 100px; white-space: nowrap;">{{title}}</div><div style="position: absolute; top: 280px; left: 0; width: 800px; text-align: center; color: rgba(255,255,255,0.95); font-size: 36px; font-weight: 500; line-height: 50px;">临时停靠 · 请多关照</div><div style="position: absolute; top: 480px; left: 0; width: 800px; text-align: center; color: #1f2937; font-size: 46px; font-weight: 900; letter-spacing: 8px; line-height: 60px;">微信扫一扫 通知我挪车</div><div style="position: absolute; top: 600px; left: 160px; width: 480px; height: 480px; background: white; border-radius: 40px; box-shadow: 0 20px 50px rgba(0,0,0,0.08); border: 2px solid #f3f4f6; box-sizing: border-box; padding: 20px;"><img src="{{qr}}" style="width: 436px; height: 436px; display: block;" /></div><div style="position: absolute; top: 1100px; left: 150px; width: 500px; height: 64px; line-height: 64px; background: #ecfdf5; color: #059669; text-align: center; border-radius: 32px; font-size: 26px; font-weight: bold;">🛡️ 虚拟安全码 · 保护车主隐私</div></div>' },
   { id: 'horizontal_dash', name: '横版仪表', thumb: '📟', html: '<div style="width: 1200px; height: 650px; background: #111827; border-radius: 40px; overflow: hidden; position: relative; font-family: sans-serif; box-sizing: border-box;"><div style="position: absolute; top: 0; right: 0; width: 550px; height: 650px; background: white;"></div><div style="position: absolute; top: 180px; left: 80px; width: 500px; color: white;"><div style="font-size: 32px; color: #10b981; font-weight: bold; letter-spacing: 4px; margin-bottom: 20px; line-height: 40px;">NOTICE</div><div style="font-size: 76px; font-weight: 900; line-height: 100px; height: 120px; margin-bottom: 20px; white-space: nowrap;">{{title}}</div><div style="font-size: 36px; color: #9ca3af; line-height: 50px;">临时停靠 · 感谢包涵</div></div><div style="position: absolute; bottom: 80px; left: 80px; color: #6b7280; font-size: 24px; font-weight: bold; line-height: 30px;">🛡️ 隐私保护通话服务</div><div style="position: absolute; top: 80px; right: 0; width: 550px; text-align: center; color: #1f2937; font-size: 36px; font-weight: 900; letter-spacing: 4px; line-height: 50px;">微信扫码 呼叫车主</div><div style="position: absolute; top: 160px; right: 95px; width: 360px; height: 360px; background: white; border-radius: 30px; box-shadow: 0 15px 35px rgba(0,0,0,0.06); border: 2px solid #f3f4f6; box-sizing: border-box; padding: 15px;"><img src="{{qr}}" style="width: 326px; height: 326px; display: block;" /></div><div style="position: absolute; bottom: 80px; right: 0; width: 550px; text-align: center; color: #10b981; font-size: 20px; font-weight: bold; line-height: 30px;">[ 请使用微信扫描上方二维码 ]</div></div>' },
   { id: 'sticker_round', name: '车窗静电贴', thumb: '🪟', html: '<div style="width: 800px; height: 800px; background: transparent; position: relative; font-family: sans-serif; box-sizing: border-box;"><div style="position: absolute; top: 20px; left: 20px; width: 760px; height: 760px; background: #fbbf24; border-radius: 380px; border: 25px solid #111827; box-sizing: border-box;"></div><div style="position: absolute; top: 60px; left: 60px; width: 680px; height: 680px; border-radius: 340px; border: 15px solid #111827; box-sizing: border-box;"></div><div style="position: absolute; top: 130px; left: 0; width: 800px; text-align: center; color: #111827; font-size: 56px; font-weight: 900; letter-spacing: 8px; line-height: 80px;">请您扫码通知我</div><div style="position: absolute; top: 230px; left: 210px; width: 380px; height: 380px; background: white; border-radius: 40px; border: 8px solid #111827; box-sizing: border-box; padding: 20px;"><img src="{{qr}}" style="width: 324px; height: 324px; display: block;" /></div><div style="position: absolute; top: 620px; left: 150px; width: 500px; height: 80px; background: white; border-radius: 40px; border: 7px solid #111827; color: #111827; font-size: 40px; font-weight: 900; box-sizing: border-box; white-space: nowrap; display: flex; justify-content: center; align-items: center; padding-bottom: 30px;">{{title}}</div></div>' },
   { id: 'photo_print', name: '相纸打印', thumb: '🖨️', html: '<div style="width: 800px; height: 1200px; background: white; position: relative; font-family: sans-serif; box-sizing: border-box;"><div style="position: absolute; top: 40px; left: 40px; width: 720px; height: 1120px; border: 2px solid #e5e7eb; box-sizing: border-box;"></div><div style="position: absolute; top: 120px; left: 0; width: 800px; text-align: center; color: #1f2937; font-size: 52px; font-weight: 900; letter-spacing: 8px; line-height: 70px;">临时停靠 · 请多关照</div><div style="position: absolute; top: 200px; left: 0; width: 800px; text-align: center; color: #6b7280; font-size: 28px; letter-spacing: 2px; line-height: 40px;">给您带来不便，敬请谅解</div><div style="position: absolute; top: 320px; left: 150px; width: 500px; height: 500px;"><img src="{{qr}}" style="width: 500px; height: 500px; display: block;" /></div><div style="position: absolute; top: 880px; left: 350px; width: 100px; height: 4px; background: #10b981;"></div><div style="position: absolute; top: 960px; left: 0; width: 800px; text-align: center; color: #111827; font-size: 48px; font-weight: bold; letter-spacing: 2px; line-height: 70px; white-space: nowrap;">{{title}}</div><div style="position: absolute; top: 1060px; left: 0; width: 800px; text-align: center; color: #9ca3af; font-size: 24px; letter-spacing: 2px; line-height: 40px;">微信扫一扫，安全联系车主</div></div>' },
   { id: 'art_gallery', name: '画廊艺术', thumb: '🖼️', html: '<div style="width: 800px; height: 1200px; background: #1a1a1a; position: relative; font-family: \'Times New Roman\', serif, sans-serif; box-sizing: border-box;"><div style="position: absolute; top: 40px; left: 40px; width: 720px; height: 1120px; border: 2px solid #c5a880; box-sizing: border-box;"></div><div style="position: absolute; top: 50px; left: 50px; width: 700px; height: 1100px; border: 1px solid rgba(197, 168, 128, 0.3); box-sizing: border-box;"></div><div style="position: absolute; top: 130px; left: 0; width: 800px; text-align: center; color: #c5a880; font-size: 26px; letter-spacing: 16px; font-weight: 300; line-height: 40px;">THE ART OF PARKING</div><div style="position: absolute; top: 200px; left: 0; width: 800px; text-align: center; color: #ffffff; font-size: 58px; letter-spacing: 28px; font-weight: bold; line-height: 80px; margin-left: 14px;">临时停靠</div><div style="position: absolute; top: 380px; left: 200px; width: 400px; height: 400px; background: white; padding: 20px; box-sizing: border-box; box-shadow: 0 20px 40px rgba(0,0,0,0.5);"><img src="{{qr}}" style="width: 360px; height: 360px; display: block;" /></div><div style="position: absolute; top: 880px; left: 350px; width: 100px; height: 2px; background: #c5a880;"></div><div style="position: absolute; top: 950px; left: 0; width: 800px; height: 100px; text-align: center; color: #ffffff; font-size: 56px; font-weight: 400; letter-spacing: 8px; line-height: 100px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; padding: 0 60px; box-sizing: border-box;">{{title}}</div><div style="position: absolute; top: 1080px; left: 0; width: 800px; text-align: center; color: rgba(255,255,255,0.5); font-size: 24px; letter-spacing: 8px; line-height: 40px;">扫 码 联 系 车 主 移 车</div></div>' },
   { id: 'pure_qr', name: '纯净原码', thumb: '🔳', html: '<div style="width: 800px; height: 800px; background: white; position: relative;"><img src="{{qr}}" style="width: 720px; height: 720px; position: absolute; top: 40px; left: 40px; display: block;" /></div>' },
   { id: 'pearl_aura', name: '珍珠贝母', thumb: '🐚', html: '<div style="width: 800px; height: 1200px; background: linear-gradient(120deg, #fdfbfb 0%, #ebedee 100%); position: relative; font-family: sans-serif; box-sizing: border-box; overflow: hidden;"><div style="position: absolute; top: -200px; right: -200px; width: 600px; height: 600px; background: radial-gradient(circle, rgba(250,208,196,0.4) 0%, transparent 70%); border-radius: 50%;"></div><div style="position: absolute; bottom: -200px; left: -200px; width: 600px; height: 600px; background: radial-gradient(circle, rgba(161,196,253,0.3) 0%, transparent 70%); border-radius: 50%;"></div><div style="position: absolute; top: 150px; left: 0; width: 800px; text-align: center; color: #a18cd1; font-size: 28px; letter-spacing: 14px; font-weight: bold;">ELEGANT PARKING</div><div style="position: absolute; top: 220px; left: 0; width: 800px; text-align: center; color: #52525b; font-size: 64px; font-weight: 300; letter-spacing: 8px;">临时停靠 · 请多关照</div><div style="position: absolute; top: 400px; left: 160px; width: 480px; height: 480px; background: rgba(255,255,255,0.6); border-radius: 40px; box-shadow: 0 20px 40px rgba(0,0,0,0.05); border: 2px solid #fff; padding: 25px; box-sizing: border-box;"><img src="{{qr}}" style="width: 426px; height: 426px; display: block; border-radius: 20px;" /></div><div style="position: absolute; top: 980px; left: 0; width: 800px; text-align: center; color: #71717a; font-size: 36px; letter-spacing: 6px;">微信扫码 呼叫车主</div><div style="position: absolute; top: 1060px; left: 0; width: 800px; text-align: center; color: #a18cd1; font-size: 22px; letter-spacing: 4px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; padding: 0 40px; box-sizing: border-box;">{{title}}</div></div>' },
   { id: 'rose_couture', name: '玫瑰高定', thumb: '🌸', html: '<div style="width: 800px; height: 1200px; background: linear-gradient(135deg, #fff1f2 0%, #fecdd3 100%); position: relative; font-family: sans-serif; box-sizing: border-box; overflow: hidden;"><div style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; background: url(\'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI4MDAiIGhlaWdodD0iMTIwMCI+PGNpcmNsZSBjeD0iMCIgY3k9IjAiIHI9IjQwMCIgZmlsbD0icmdiYSgyNTUsMjU1LDI1NSwwLjUpIi8+PGNpcmNsZSBjeD0iODAwIiBjeT0iMTIwMCIgIHI9IjUwMCIgZmlsbD0icmdiYSgyNTUsMjU1LDI1NSwwLjQpIi8+PC9zdmc+\') no-repeat center center;"></div><div style="position: absolute; top: 140px; left: 0; width: 800px; text-align: center; color: #be185d; font-size: 24px; letter-spacing: 12px; font-weight: bold;">TEMPORARY PARKING</div><div style="position: absolute; top: 200px; left: 0; width: 800px; text-align: center; color: #831843; font-size: 64px; letter-spacing: 6px; font-weight: 900; line-height: 80px; white-space: nowrap;">临时停靠 · 烦请见谅</div><div style="position: absolute; top: 400px; left: 160px; width: 480px; height: 480px; background: rgba(255,255,255,0.9); border-radius: 40px; box-shadow: 0 30px 60px rgba(190, 24, 93, 0.15); border: 2px solid #fff; box-sizing: border-box; padding: 25px;"><img src="{{qr}}" style="width: 426px; height: 426px; display: block; border-radius: 20px;" /></div><div style="position: absolute; top: 960px; left: 0; width: 800px; text-align: center; color: #9f1239; font-size: 42px; font-weight: bold; letter-spacing: 4px;">微信扫一扫 呼叫车主</div><div style="position: absolute; top: 1060px; left: 0; width: 800px; text-align: center; color: #e11d48; font-size: 24px; letter-spacing: 2px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; padding: 0 40px; box-sizing: border-box;">{{title}}</div></div>' },
   { id: 'french_chic', name: '法式轻奢', thumb: '💎', html: '<div style="width: 800px; height: 1200px; background: #fafaf9; position: relative; font-family: \'Times New Roman\', serif; box-sizing: border-box;"><div style="position: absolute; top: 30px; left: 30px; width: 740px; height: 1140px; border: 1px solid #1c1917; box-sizing: border-box;"></div><div style="position: absolute; top: 40px; left: 40px; width: 720px; height: 1120px; border: 3px solid #1c1917; box-sizing: border-box;"></div><div style="position: absolute; top: 160px; left: 0; width: 800px; text-align: center; color: #1c1917; font-size: 32px; letter-spacing: 24px; font-weight: 300; margin-left: 12px;">EXCUSEZ-MOI</div><div style="position: absolute; top: 250px; left: 0; width: 800px; text-align: center; color: #1c1917; font-size: 54px; letter-spacing: 12px; font-weight: bold; line-height: 80px; font-family: sans-serif; margin-left: 6px; white-space: nowrap;">麻烦您扫码通知挪车</div><div style="position: absolute; top: 420px; left: 200px; width: 400px; height: 400px; background: #fff; border: 2px solid #e7e5e4; padding: 15px; box-sizing: border-box; box-shadow: 0 10px 30px rgba(0,0,0,0.05);"><img src="{{qr}}" style="width: 366px; height: 366px; display: block;" /></div><div style="position: absolute; top: 920px; left: 300px; width: 200px; height: 1px; background: #1c1917;"></div><div style="position: absolute; top: 960px; left: 0; width: 800px; text-align: center; color: #44403c; font-size: 28px; font-family: sans-serif; letter-spacing: 4px;">感谢您的宽容与理解</div><div style="position: absolute; top: 1050px; left: 0; width: 800px; text-align: center; color: #a8a29e; font-size: 20px; font-family: sans-serif; letter-spacing: 2px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; padding: 0 40px; box-sizing: border-box;">{{title}}</div></div>' },
   { id: 'ruby_velvet', name: '红丝绒', thumb: '🍷', html: '<div style="width: 800px; height: 1200px; background: #4c0519; position: relative; font-family: sans-serif; box-sizing: border-box;"><div style="position: absolute; top: 40px; left: 40px; width: 720px; height: 1120px; border: 2px solid #9f1239; box-sizing: border-box;"></div><div style="position: absolute; top: 160px; left: 0; width: 800px; text-align: center; color: #fda4af; font-size: 24px; letter-spacing: 16px; font-weight: bold;">PRIVATE PARKING</div><div style="position: absolute; top: 230px; left: 0; width: 800px; text-align: center; color: #fff1f2; font-size: 58px; font-weight: bold; letter-spacing: 12px; margin-left: 6px;">临时停靠</div><div style="position: absolute; top: 400px; left: 180px; width: 440px; height: 440px; background: #881337; border-radius: 20px; padding: 20px; box-sizing: border-box; box-shadow: 0 30px 60px rgba(0,0,0,0.4);"><img src="{{qr}}" style="width: 400px; height: 400px; display: block; border-radius: 10px;" /></div><div style="position: absolute; top: 960px; left: 0; width: 800px; text-align: center; color: #fecdd3; font-size: 32px; letter-spacing: 8px;">烦 请 扫 码 联 系</div><div style="position: absolute; top: 1060px; left: 0; width: 800px; text-align: center; color: #be185d; font-size: 20px; letter-spacing: 2px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; padding: 0 40px; box-sizing: border-box;">{{title}}</div></div>' },
   { id: 'titanium_forge', name: '钛金铠甲', thumb: '🛡️', html: '<div style="width: 800px; height: 1200px; background: linear-gradient(135deg, #27272a 0%, #09090b 100%); position: relative; font-family: sans-serif; box-sizing: border-box;"><div style="position: absolute; top: 0; left: 0; width: 800px; height: 12px; background: linear-gradient(90deg, #d6d3d1, #78716c, #d6d3d1);"></div><div style="position: absolute; top: 150px; left: 0; width: 800px; text-align: center; color: #a8a29e; font-size: 32px; font-weight: 900; letter-spacing: 20px;">NOTICE</div><div style="position: absolute; top: 230px; left: 0; width: 800px; text-align: center; color: #f5f5f4; font-size: 72px; font-weight: 900; letter-spacing: 8px; white-space: nowrap;">临 时 停 靠</div><div style="position: absolute; top: 400px; left: 160px; width: 480px; height: 480px; background: linear-gradient(145deg, #3f3f46, #1c1917); border-radius: 24px; padding: 25px; box-sizing: border-box; box-shadow: inset 0 2px 4px rgba(255,255,255,0.1), 0 25px 50px rgba(0,0,0,0.8); border: 1px solid #57534e;"><img src="{{qr}}" style="width: 426px; height: 426px; display: block; border-radius: 12px;" /></div><div style="position: absolute; top: 960px; left: 0; width: 800px; text-align: center; color: #d6d3d1; font-size: 36px; font-weight: bold; letter-spacing: 6px;">微信扫码 · 通知挪车</div><div style="position: absolute; top: 1060px; left: 0; width: 800px; text-align: center; color: #78716c; font-size: 24px; letter-spacing: 4px; text-transform: uppercase; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; padding: 0 40px; box-sizing: border-box;">{{title}}</div></div>' },
   { id: 'racing_carbon', name: '赛道竞速', thumb: '🏎️', html: '<div style="width: 800px; height: 1200px; background: #020617; position: relative; font-family: sans-serif; box-sizing: border-box; overflow: hidden;"><div style="position: absolute; top: -100px; left: 300px; width: 200px; height: 1400px; background: #0ea5e9; transform: rotate(15deg); opacity: 0.1;"></div><div style="position: absolute; top: 140px; left: 80px; width: 700px; border-left: 8px solid #0ea5e9; padding-left: 20px; box-sizing: border-box;"><div style="color: #38bdf8; font-size: 24px; font-weight: 900; letter-spacing: 4px;">MOVE VEHICLE</div><div style="color: #f8fafc; font-size: 58px; font-weight: 900; letter-spacing: 2px; margin-top: 10px; white-space: nowrap;">临时停靠 · 请多关照</div></div><div style="position: absolute; top: 380px; left: 160px; width: 480px; height: 480px; background: rgba(15, 23, 42, 0.8); border: 2px solid #0ea5e9; box-sizing: border-box; padding: 25px; box-shadow: 0 0 40px rgba(14, 165, 233, 0.3);"><img src="{{qr}}" style="width: 426px; height: 426px; display: block;" /></div><div style="position: absolute; top: 960px; left: 0; width: 800px; text-align: center; color: #e0f2fe; font-size: 40px; font-weight: 900; letter-spacing: 8px;">扫码呼叫车主</div><div style="position: absolute; top: 1050px; left: 0; width: 800px; text-align: center; color: #38bdf8; font-size: 24px; letter-spacing: 4px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; padding: 10px 40px 20px 40px; box-sizing: border-box; line-height: 1.5;">{{title}}</div></div>' },
   { id: 'creamy_sweet', name: '奶油甜心', thumb: '🍰', html: '<div style="width: 800px; height: 1200px; background: linear-gradient(180deg, #fffbeb 0%, #fde68a 100%); position: relative; font-family: sans-serif; box-sizing: border-box; overflow: hidden; border: 15px solid #fbbf24; border-radius: 60px;"><div style="position: absolute; top: -50px; left: -50px; width: 300px; height: 300px; background: #fef3c7; border-radius: 50%; opacity: 0.8;"></div><div style="position: absolute; bottom: -100px; right: -50px; width: 400px; height: 400px; background: #fcd34d; border-radius: 50%; opacity: 0.6;"></div><div style="position: absolute; top: 120px; width: 100%; text-align: center; color: #d97706; font-size: 40px; font-weight: 900; letter-spacing: 4px;">૮( ˶ᵔ ᵕ 随叫随到 ᵔ˶ )ა</div><div style="position: absolute; top: 200px; width: 100%; text-align: center; color: #b45309; font-size: 72px; font-weight: 900; letter-spacing: 2px;">滴滴！请扫码</div><div style="position: absolute; top: 380px; left: 160px; width: 480px; height: 480px; background: white; border-radius: 60px; box-shadow: 0 20px 40px rgba(217, 119, 6, 0.15); border: 8px dashed #fcd34d; box-sizing: border-box; padding: 25px;"><img src="{{qr}}" style="width: 414px; height: 414px; display: block; border-radius: 30px;" /></div><div style="position: absolute; top: 940px; width: 100%; text-align: center; color: #d97706; font-size: 36px; font-weight: bold; letter-spacing: 2px;">🚗 抱歉占位 · 马上就来 🚗</div><div style="position: absolute; top: 1050px; width: 100%; text-align: center; background: #b45309; color: #fffbeb; font-size: 26px; padding: 15px 0; font-weight: bold; letter-spacing: 2px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; box-sizing: border-box;">{{title}}</div></div>' },
   { id: 'cloud_bubble', name: '云朵泡泡', thumb: '☁️', html: '<div style="width: 800px; height: 1200px; background: #e0f2fe; position: relative; font-family: sans-serif; box-sizing: border-box; overflow: hidden;"><div style="position: absolute; top: 0; left: 0; width: 100%; height: 350px; background: #bae6fd; border-bottom-left-radius: 50% 20%; border-bottom-right-radius: 50% 20%;"></div><div style="position: absolute; top: 100px; width: 100%; text-align: center; color: #0284c7; font-size: 80px; font-weight: 900; letter-spacing: 6px; text-shadow: 4px 4px 0px #fff;">临时停靠</div><div style="position: absolute; top: 220px; width: 100%; text-align: center; color: #0369a1; font-size: 32px; font-weight: bold; letter-spacing: 4px;">SORRY FOR WAITING ☁️</div><div style="position: absolute; top: 380px; left: 160px; width: 480px; height: 480px; background: rgba(255,255,255,0.9); border-radius: 50px; box-shadow: 0 30px 60px rgba(2, 132, 199, 0.15); box-sizing: border-box; padding: 30px;"><img src="{{qr}}" style="width: 420px; height: 420px; display: block; border-radius: 20px;" /></div><div style="position: absolute; top: 920px; width: 100%; text-align: center; color: #0284c7; font-size: 42px; font-weight: 900; letter-spacing: 8px;">扫 码 呼 叫 车 主</div><div style="position: absolute; top: 1040px; left: 150px; width: 500px; text-align: center; background: #fff; color: #0ea5e9; font-size: 24px; padding: 15px 40px; border-radius: 30px; font-weight: bold; box-shadow: 0 10px 20px rgba(2, 132, 199, 0.05); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; box-sizing: border-box;">{{title}}</div></div>' },
   { id: 'neon_cyber', name: '霓虹电音', thumb: '⚡', html: '<div style="width: 800px; height: 1200px; background: #09090b; position: relative; font-family: sans-serif; box-sizing: border-box; overflow: hidden; border: 4px solid #3b82f6;"><div style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; background: repeating-linear-gradient(45deg, transparent, transparent 10px, rgba(56, 189, 248, 0.05) 10px, rgba(56, 189, 248, 0.05) 20px);"></div><div style="position: absolute; top: 120px; width: 100%; text-align: center; color: #f43f5e; font-size: 85px; font-weight: 900; font-style: italic; letter-spacing: 4px; text-shadow: 4px 4px 0px #0ea5e9, -2px -2px 0px #eab308;">EMERGENCY</div><div style="position: absolute; top: 240px; width: 100%; text-align: center; color: #fff; font-size: 40px; font-weight: 900; letter-spacing: 12px; text-shadow: 0 0 10px #38bdf8;">临·时·停·靠</div><div style="position: absolute; top: 400px; left: 160px; width: 480px; height: 480px; background: #000; border: 4px solid #f43f5e; box-shadow: 0 0 30px rgba(244, 63, 94, 0.4), inset 0 0 20px rgba(14, 165, 233, 0.4); box-sizing: border-box; padding: 20px; transform: skewX(-2deg);"><img src="{{qr}}" style="width: 432px; height: 432px; display: block;" /></div><div style="position: absolute; top: 950px; width: 100%; text-align: center; color: #10b981; font-size: 45px; font-weight: 900; letter-spacing: 6px; text-shadow: 0 0 15px rgba(16, 185, 129, 0.6);">⚡ 扫码直连 极速响应 ⚡</div><div style="position: absolute; top: 1060px; left: 100px; width: 600px; text-align: center; color: #38bdf8; font-size: 24px; font-family: monospace; letter-spacing: 2px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; box-sizing: border-box; padding: 20px 20px 20px 20px; border-top: 1px dashed #38bdf8; line-height: 1.5;">{{title}}</div></div>' }
];

// 🌟 新增：供前端页面获取海报模板的接口 (支持热更新)
router.get('/templates', async (req, res) => {
    try {
        const kvData = await redisClient.get('movecar:settings:templates');
        if (kvData) {
            return res.json({ success: true, data: JSON.parse(kvData) });
        }
        return res.json({ success: true, data: defaultTemplates });
    } catch (e) {
        return res.json({ success: false, data: defaultTemplates });
    }
});

router.post('/notify', async (req, res) => {
    const userKey = (req.query.u || 'default').toLowerCase();
    try {
        const lockKey = "movecar:lock:" + userKey;
        if (await redisClient.get(lockKey)) return res.status(429).json({ success: false, error: '发送频率过快' });

        const body = req.body;
        const config = await getUserConfig(userKey);
        const sys = await getSystemSettings(); 
        
        const carTitle = config.carTitle || '车主';
        const domain = await getBaseDomain();
        const safeDomain = domain || `${req.protocol}://${req.get('host')}`;
        const confirmUrl = `${safeDomain}/owner-confirm?u=${userKey}`;

        const notifyTitle = `🚗 挪车请求：${carTitle}`;
        const notifyContent = `💬 留言内容：${body.message || '车旁有人等待，请速来挪车。'}`;
        
        if (body.location && body.location.lat) {
            const maps = generateMapUrls(body.location.lat, body.location.lng);
            await redisClient.set("movecar:loc:" + userKey, JSON.stringify({ ...body.location, ...maps }), { EX: CONFIG.KV_TTL });
        }
        await redisClient.set("movecar:status:" + userKey, JSON.stringify({ status: 'waiting', sessionId: body.sessionId }), { EX: CONFIG.SESSION_TTL });
        await redisClient.set(lockKey, '1', { EX: CONFIG.RATE_LIMIT_TTL });

        const tasks = [];
        if (config.pushplusToken) tasks.push(Notifier.sendPushPlus(config.pushplusToken, notifyTitle, notifyContent, confirmUrl));
        if (config.barkUrl) tasks.push(Notifier.sendBark(config.barkUrl, notifyTitle, notifyContent, confirmUrl));
        if (sys.wxpusherAppToken && config.wxpusherUid) tasks.push(Notifier.sendWxPusher(sys.wxpusherAppToken, config.wxpusherUid, notifyTitle, notifyContent, confirmUrl));
        if (config.serverChanKey) tasks.push(Notifier.sendServerChan(config.serverChanKey, notifyTitle, notifyContent, confirmUrl));
        if (sys.tgBotToken && config.tgChatId) tasks.push(Notifier.sendTelegram(sys.tgBotToken, config.tgChatId, notifyTitle, notifyContent, confirmUrl));
        if (config.wecomUrl) tasks.push(Notifier.sendWeCom(config.wecomUrl, notifyTitle, notifyContent, confirmUrl));
        if (config.dingtalkUrl) tasks.push(Notifier.sendDingTalk(config.dingtalkUrl, notifyTitle, notifyContent, confirmUrl));
        if (config.webhookUrl) tasks.push(Notifier.sendWebhook(config.webhookUrl, notifyTitle, notifyContent, confirmUrl));
        if (sys.smtpHost && config.email) tasks.push(Notifier.sendEmail(sys, config.email, notifyTitle, notifyContent, confirmUrl));

        Promise.all(tasks); 
        return res.json({ success: true });
    } catch (e) {
        console.error('Notify Error:', e);
        return res.status(500).json({ success: false, error: '系统内部错误' });
    }
});

router.get('/check-status', async (req, res) => {
    const userKey = (req.query.u || 'default').toLowerCase();
    const clientSessionId = req.query.s;

    const data = await redisClient.get("movecar:status:" + userKey);
    if (!data) return res.json({ status: 'none' });

    const statusObj = JSON.parse(data);
    if (statusObj.sessionId !== clientSessionId) return res.json({ status: 'none' });

    const ownerLoc = await redisClient.get("movecar:owner_loc:" + userKey);
    return res.json({ status: statusObj.status, ownerLocation: ownerLoc ? JSON.parse(ownerLoc) : null });
});

router.get('/get-location', async (req, res) => {
    const userKey = (req.query.u || 'default').toLowerCase();
    const data = await redisClient.get("movecar:loc:" + userKey);
    res.setHeader('Content-Type', 'application/json');
    res.send(data || '{}');
});

router.post('/owner-confirm', async (req, res) => {
    const userKey = (req.query.u || 'default').toLowerCase();
    const body = req.body;
    
    const data = await redisClient.get("movecar:status:" + userKey);
    if (data) {
        const statusObj = JSON.parse(data);
        statusObj.status = 'confirmed'; 
        if (body.location) {
            const urls = generateMapUrls(body.location.lat, body.location.lng);
            await redisClient.set("movecar:owner_loc:" + userKey, JSON.stringify({ ...body.location, ...urls }), { EX: 600 });
        }
        await redisClient.set("movecar:status:" + userKey, JSON.stringify(statusObj), { EX: 600 });
    }
    return res.json({ success: true });
});

module.exports = router;